mouseheatmap/mouseheatmap/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('mouseheatmapapp/', include('mouseheatmapapp.urls')),
    path('admin/', admin.site.urls)
]

mouseheatmap/mouseheatmapapp/urls.py
from django.urls import path

from . import views

app_name = 'mouseheatmapapp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('read_minmax/', views.ReadMinMaxView.read, name='read_minmax'),
    # path(url(r'^gen_durationtimehm/(?P<value>\d+)/$'), views.GenDurationTimeHMView.as_view(), name='gen_durationtimehm'),
    path('gen_mousemovementhm/<int:use_value>/', views.GenMouseMovementHMView.as_view(), name='gen_mousemovementhm'),
    path('gen_durationtimehm/<int:use_value>/', views.GenDurationTimeHMView.as_view(), name='gen_durationtimehm'),
    path('gen_mouseclickhm/<int:use_value>/', views.GenMouseClickHMView.as_view(), name='gen_mouseclickhm'),
    path("get_path/", views.
    getpath, name="get_path"),
]

mouseheatmap/mouseheatmapapp/models.py
import datetime
from turtle import update
from django.db import models
from django.utils import timezone
from django.contrib import admin

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class InitialData(models.Model):
    folder_path = models.CharField(max_length=255,default='')
    min_duration_time = models.IntegerField(default=0)
    max_duration_time = models.IntegerField(default=0)
    min_mouse_movement = models.IntegerField(default=0)
    max_mouse_movement = models.IntegerField(default=0)
    min_mouse_click = models.IntegerField(default=0)
    max_mouse_click = models.IntegerField(default=0)
    pub_date = models.DateTimeField(auto_now=True)

mouseheatmap/mouseheatmapapp/forms.py
from django import forms
from mouseheatmapapp.models import InitialData

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class GetPathForm(forms.ModelForm):
    folder_path = forms.CharField(required=True)
    folder_path.widget = forms.TextInput(attrs={'size': 100, 'title': 'Search',})

    def clean_renewal_date(self):
        data = self.cleaned_data['folder_path']

        # Check if a date is not empty.
        if data == "":
            raise ValidationError(_('Invalid folder path - empty path'))

        # Remember to always return the cleaned data.
        return data

    class Meta:
        model = InitialData
        fields = ['folder_path']

mouseheatmap/mouseheatmapapp/views.py
#from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from mouseheatmapapp.forms import GetPathForm
from mouseheatmapapp.models import Choice, Question, InitialData

import pandas as pd
import glob
import os

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'mouseheatmapapp/index.html'
    context_object_name = 'initialdata'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        # return Question.objects.filter(
        #     pub_date__lte=timezone.now()
        # ).order_by('-pub_date')[:5]
        return InitialData.objects.filter(id=1)

class DetailView(generic.DetailView):
    model = Question
    template_name = 'mouseheatmapapp/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'mouseheatmapapp/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'mouseheatmapapp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('mouseheatmapapp:results', args=(question.id,)))

class ReadMinMaxView(generic.ListView):
    model = InitialData
    template_name = 'mouseheatmapapp/read_minmax.html'
    context_object_name = 'latest_heatmap_info_list'

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

    def read(request): 
        # path = r'C:\OpalData\Work\FundEducation\Research\MouseHeatmap\PreExperiment\MouseData\csv_file' # use your path
        # all_files = glob.glob(os.path.join(path , "/*.csv"))

        # li = []

        # for filename in all_files:
        #     df = pd.read_csv(filename, index_col=None, header=1)
        #     li.append(df)

        # frame = pd.concat(li, axis=0, ignore_index=True)

        obj = InitialData.objects.filter(id=1)
        path=obj.values('folder_path').first()['folder_path']
        # Get CSV files list from a folder
        # path = 'C:\OpalData\Work\FundEducation\Research\MouseHeatmap\PreExperiment\MouseData\csv_file'
        csv_files = glob.glob(path + "\*.csv")

        # Read each CSV file into DataFrame
        # This creates a list of dataframes
        df_lists1 = (pd.read_csv(file) for file in csv_files)
        # Create new column name 'DURATION_TIME_MS' for each df_list
        print("Datatype is ")
        print(type(df_lists1))
        my_list = list(df_lists1)
        print(type(my_list))
        print(type(my_list[0]))
        print(my_list[0].get('UNIX_TIMESTAMP_MS'))
        i = 0
        # Compute Duration Time and max-min total of all csv file
        mouse_movement_min=99999999
        mouse_movement_max=0

        mouse_click_min=99999999
        mouse_click_max=0
        for x in my_list:
            print("i="+str(i))
            print(x.get('UNIX_TIMESTAMP_MS'))

            # Find min-max value of Mouse movement data in each df
            mm_min = x.groupby(['CLIENTX', 'CLIENTY']).size().min(axis = 0, skipna = True)
            mm_max = x.groupby(['CLIENTX', 'CLIENTY']).size().max(axis = 0, skipna = True)
            print('mm_min=' + str(mm_min))
            print('mm_max=' + str(mm_max))
            if(mouse_movement_min>mm_min):
                mouse_movement_min=mm_min
            if(mouse_movement_max<mm_max):
                mouse_movement_max=mm_max
            
            # Find min-max value of Mouse click data in each df
            # print(type(x.info()))
            x_filter = x.query("MOUSE_CLICKED == True")
            print(x_filter)
            mc_min = x_filter.groupby(['CLIENTX', 'CLIENTY']).size().min(axis = 0, skipna = True)
            mc_max = x_filter.groupby(['CLIENTX', 'CLIENTY']).size().max(axis = 0, skipna = True)
            print('mc_min=' + str(mc_min))
            print('mc_max=' + str(mc_max))
            if(mouse_click_min>mc_min):
                mouse_click_min=mc_min
            if(mouse_click_max<mc_max):
                mouse_click_max=mc_max

            # Compute Duration Time
            j=0
            #for y in x.get('UNIX_TIMESTAMP_MS'):
            duration_value=[]
            print(len(x.index))
            while j < len(x.index):
                if j < (len(x.index)-1):
                    # print("i="+str(i)+" j="+str(j))
                    # print(x.at[j,'UNIX_TIMESTAMP_MS'])
                    duration_value.append(int(x.at[j+1,'UNIX_TIMESTAMP_MS']) - int(x.at[j,'UNIX_TIMESTAMP_MS']))
                else:
                    duration_value.append(0)
                j += 1
            x.insert(1,"DURATION_TIME",duration_value,allow_duplicates=True)
            i += 1


        # Concatenate all DataFrames
        all_df = pd.concat(my_list, ignore_index=True)
        # find min-max value of DURATION_TIME in all_df
        duration_time_min=all_df['DURATION_TIME'].min(axis = 0, skipna = True)
        duration_time_max=all_df['DURATION_TIME'].max(axis = 0, skipna = True)

        print("Mouse Movement Min:"+str(mouse_movement_min))
        print("Mouse Movement Max:"+str(mouse_movement_max))
        print("Duration Time Min:"+str(duration_time_min))
        print("Duration Time Max:"+str(duration_time_max))
        print("Mouse Click Min:"+str(mouse_click_min))
        print("Mouse Click Max:"+str(mouse_click_max))

        # insert or update min-max value of DURATION_TIME in DB
        # get item or create new one if it doesn't exist
        # item, created = InitialData.objects.filter(id=1).get_or_create(
        #     min_duration_time=duration_time_min,
        #     max_duration_time=duration_time_max,
        # )
        # # if it already exist, update quantity
        # if not created:
        #     item.min_duration_time = duration_time_min
        #     item.max_duration_time = duration_time_max
        # # whether item was created or updated save it to database
        # item.save()

        # try:
        #     obj = InitialData.objects.filter(id=1).update(
        #         min_duration_time=duration_time_min,
        #         max_duration_time=duration_time_max
        #         )
        # except InitialData.DoesNotExist:
        #     InitialData.objects.create(
        #         min_duration_time=duration_time_min,
        #         max_duration_time=duration_time_max
        # )

        obj = InitialData.objects.filter(id=1)
        if obj.exists():
            obj.update(
                min_duration_time=duration_time_min,
                max_duration_time=duration_time_max,
                min_mouse_movement=mouse_movement_min,
                max_mouse_movement=mouse_movement_max,
                min_mouse_click=mouse_click_min,
                max_mouse_click=mouse_click_max
                )
        else:
            InitialData.objects.create(
                min_duration_time=duration_time_min,
                max_duration_time=duration_time_max,
                min_mouse_movement=mouse_movement_min,
                max_mouse_movement=mouse_movement_max,
                min_mouse_click=mouse_click_min,
                max_mouse_click=mouse_click_max
                )

        # all_df.info(verbose=True)
        # return render(request, 'mouseheatmapapp/index.html', {'data': all_df})
        # response = redirect('http://127.0.0.1:8000/mouseheatmapapp/')
        # return response
        return HttpResponseRedirect(reverse('mouseheatmapapp:index'))

class GenDurationTimeHMView(generic.ListView):
    template_name = 'mouseheatmapapp/gen_durationtimehm.html'
    context_object_name = 'initialdata'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['use_value'] = self.kwargs['use_value']
        return context

    def get_queryset(self):
        return InitialData.objects.filter(id=1)

class GenMouseMovementHMView(generic.ListView):
    template_name = 'mouseheatmapapp/gen_mousemovementhm.html'
    context_object_name = 'initialdata'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['use_value'] = self.kwargs['use_value']
        return context

    def get_queryset(self):
        return InitialData.objects.filter(id=1)

class GenMouseClickHMView(generic.ListView):
    template_name = 'mouseheatmapapp/gen_mouseclickhm.html'
    context_object_name = 'initialdata'
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['use_value'] = self.kwargs['use_value']
        return context

    def get_queryset(self):
        return InitialData.objects.filter(id=1)

def getpath(request):
    """View function for renewing a specific BookInstance by librarian."""
    obj = InitialData.objects.filter(id=1)

mouseheatmap/mouseheatmapapp/templates/mouseheatmapapp/detail.html
<form action="{% url 'mouseheatmapapp:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

mouseheatmap/mouseheatmapapp/templates/mouseheatmapapp/gen_durationtimehm.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8" />
    <title>Mouse Duration Heatmap Example</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="index, follow" />
    <meta name="description" content="This example shows how to use dynamic legends and tooltips with heatmap.js" />
    <meta name="keywords" content="tooltip, heatmap, heatmap.js legend, heatmap legend" />
    <link rel="stylesheet" href="https://www.patrick-wied.at/static/heatmapjs/assets/css/commons.css" />
    <link rel="stylesheet" href="https://www.patrick-wied.at/static/heatmapjs/assets/css/example-commons.css" />
    <style>
        body, html { margin:0; padding:0; height:100%;}
        body { font-family:sans-serif; }
        body * { font-weight:200;}
        .heatmapContainerWrapper { width:100%; height:100%; position:absolute; }
        .heatmapContainer { width:100%; height:100%;}
        .legend-area { position:absolute; bottom:0; right:0; padding:10px; background:white; outline:3px solid black; line-height:1em; }
        h4 { margin:0; padding:0; margin-bottom:5px;}
        #min { float:left; }
        #max { float:right; }
        span { font-size:14px; margin:0; padding:0; }
        .tooltip { position:absolute; left:0; top:0; background:rgba(0,0,0,.8); color:white; font-size:14px; padding:5px; line-height:18px; display:none;}
    </style>
    <link rel="stylesheet" href="https://www.patrick-wied.at/static/heatmapjs/assets/third-party/prism/prism.css" />
</head>
<body>
    <div class="heatmapContainerWrapper">
      <div class="heatmapContainer">

      </div>
      <div class="tooltip"></div>
     <div class="legend-area">
       <h4>Data Color</h4>
       <span id="min"></span>
       <span id="max"></span>
       <img id="gradient" src="" style="width:100%" />
      </div>
    </div>
  <script src="https://www.patrick-wied.at/static/heatmapjs/assets/js/heatmap.min.js"></script>
  <script>
    window.onload = function() {
      /*  legend code */
      // we want to display the gradient, so we have to draw it
      var legendCanvas = document.createElement('canvas');
      legendCanvas.width = 100;
      legendCanvas.height = 10;
      var min = document.querySelector('#min');
      var max = document.querySelector('#max');
      var gradientImg = document.querySelector('#gradient');

      var legendCtx = legendCanvas.getContext('2d');
      var gradientCfg = {};

      function updateLegend(data) {
        // the onExtremaChange callback gives us min, max, and the gradientConfig
        // so we can update the legend
        console.log("max in updateLegend:"+data.max);
        console.log("min in updateLegend:"+data.min);
        min.innerHTML = data.min;
        max.innerHTML = data.max;
        // regenerate gradient image
        if (data.gradient != gradientCfg) {
          gradientCfg = data.gradient;
          var gradient = legendCtx.createLinearGradient(0, 0, 100, 1);
          for (var key in gradientCfg) {
            gradient.addColorStop(key, gradientCfg[key]);
          }

          legendCtx.fillStyle = gradient;
          legendCtx.fillRect(0, 0, 100, 10);
          gradientImg.src = legendCanvas.toDataURL();
        }
      };
      /* legend code end */
      heatmapData = JSON.parse(sessionStorage.getItem("heatmapData"));
      //console.log(heatmapData);
      //console.log(heatmapData.data.length);
      var heatmapInstance = h337.create({
        container: document.querySelector('.heatmapContainer'),
        useLocalExtrema: false,
        onExtremaChange: function(data) {
          updateLegend(data);
        },
        // the maximum opacity (the value with the highest intensity will have it)
        maxOpacity: 1,
        // minimum opacity. any value > 0 will produce
        // no transparent gradient transition
        //minOpacity: 0.1,
        radius: 15,
        blur: .90,
        // backgroundColor with alpha so you can see through it
        backgroundColor: 'rgba(255, 255, 255, 0.96)'
      });
      console.log("heatmapInstance:"+JSON.stringify(heatmapInstance));
      //จัดรูปแบบสำหรับแสดงผลบน heatmap.js
      heatmapData = heatmapData.data.map(function(obj) {
        return { x: obj.CLIENTX, y: obj.CLIENTY, value: obj.DURATION_TIME_MS };
      });

      //รวม heatmapData ที่มีค่า x และ y ทีซ้ำกัน โดยการ value++
      combineValueDupicateXY(heatmapData);
      
      //find min and max value
      var maxValue= 0;
      var minValue= 9999999;
      {% if use_value == 1 %}
        //alert("use_value = 1");
        {% for data in initialdata %}
            minValue = {{data.min_duration_time}}
            maxValue = {{data.max_duration_time}}
        {% endfor %}
      {% else %}
        //alert("use_value = 0");
        for(var i = 0; i <  heatmapData.length; i++) {
            if(maxValue < parseInt(heatmapData[i].value)){
            maxValue = parseInt( heatmapData[i].value);
            }
            if(minValue > parseInt(heatmapData[i].value)){
            minValue = parseInt(heatmapData[i].value);
            }
        }
      {% endif %}
      console.log("max:"+maxValue);
      console.log("min:"+minValue);
      inputHeatmapData = {
        min: minValue,
        max: maxValue,
        data: heatmapData
      }
      console.log("Test:"+JSON.stringify(inputHeatmapData));
      heatmapInstance.setData(inputHeatmapData);  

      var demoWrapper = document.querySelector('.heatmapContainerWrapper');
      var tooltip = document.querySelector('.tooltip');

      function updateTooltip(x, y, value) {
        // + 15 for distance to cursor
        var transform = 'translate(' + (x + 15) + 'px, ' + (y + 15) + 'px)';
        tooltip.style.MozTransform = transform; /* Firefox */
        tooltip.style.msTransform = transform; /* IE (9+) - note ms is lowercase */
        tooltip.style.OTransform = transform; /* Opera */
        tooltip.style.WebkitTransform = transform; /* Safari and Chrome */
        tooltip.style.transform = transform; /* One day, my pretty */
        tooltip.innerHTML = value;
      }

      demoWrapper.onmousemove = function(ev) {
        var x = ev.layerX;
        var y = ev.layerY;
        var value = heatmapInstance.getValueAt({
          x: x,
          y: y
        });

        tooltip.style.display = 'block';

        updateTooltip(x, y, value);
      };
      demoWrapper.onmouseout = function() {
        tooltip.style.display = 'none';
      };
      function combineValueDupicateXY(inputData) {
        //รวม heatmapData ที่มีค่า x และ y ทีซ้ำกัน โดยการ value++
        console.log("Before:"+JSON.stringify(inputData));
        for(var i = 0; i < inputData.length; i++) {
          for(var j = i+1; j < inputData.length; j++){
            if(inputData[i].x == inputData[j].x && inputData[i].y == inputData[j].y){
              console.log('in if ('+i+','+j+') "x":"'+inputData[i].x+'","y":"'+inputData[i].y+'"');
              inputData[i].value++;
              inputData.splice(j,1);
              j--;
              //console.log('length:'+inputData.length);
            }
          }
        }
      }
    };
  </script>
  <script src="https://www.patrick-wied.at/static/heatmapjs/assets/third-party/prism/prism.js"></script>
</body>
</html>

mouseheatmap/mouseheatmapapp/templates/mouseheatmapapp/get_path.html
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Read Min-Max Value">
  </form>
{% endblock %}

mouseheatmap/mouseheatmapapp/templates/mouseheatmapapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <title>Mousemove example (with backgroundColor) | heatmap.js</title>
    <script src="https://unpkg.com/papaparse@latest/papaparse.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="{% static 'mouseheatmapapp/style.css' %}">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
</head>
<body>
    <a href="{% url 'mouseheatmapapp:get_path' %}">Read New Values of All Duration Time Min-Max</a>
    {% if initialdata %}
        <ul>
        {% for data in initialdata %}
            <li>Current folder path : {{data.folder_path}}</li>
            <li>Total Mouse Movement Min : {{data.min_mouse_movement}} and Max : {{data.max_mouse_movement}}</li>
            <li>Total Duration Time Min : {{data.min_duration_time}} and Max : {{data.max_duration_time}}</li>
            <li>Total Mouse Click Min : {{data.min_mouse_click}} and Max : {{data.max_mouse_click}}</li>
        {% endfor %}
        </ul>
    {% else %}
        <ul>
            <li>Total Duration Time Min : 0</li>
            <li>Total Duration Time Max : 0</li>
        </ul>
    {% endif %}
    
    <form id="myForm" method="post">
        {% csrf_token %}
        <input type="file" id="csvFile" accept=".csv" />
        <br />
        <input type="hidden" id="heatmapdata" />
        <input type="submit" value="Read Data" />
    </form>
    <script>
        const myForm = document.getElementById("myForm");
        const csvFile = document.getElementById("csvFile");
        const useallminmax = document.getElementById("useallminmax");
        myForm.addEventListener("submit", function (e) {
            e.preventDefault();
            Papa.parse(csvFile.files[0], {
                complete: function (results) {
                    console.log(results);
                    //find durationTimeTotal of user in milisecond and min unit.
                    var durationTimeTotal =(results.data[results.data.length-1].UNIX_TIMESTAMP_MS) - (results.data[0].UNIX_TIMESTAMP_MS);
                    document.write('<a href="{% url 'mouseheatmapapp:read_minmax' %}">Read New Values of All Duration Time Min-Max</a>');
                    {% if initialdata %}
                        document.write('<ul>');
                        {% for data in initialdata %}
                            document.write('<li>Current folder path : {{data.folder_path}}</li>');
                            document.write('<li>Total Duration Time Min : {{data.min_duration_time}} and Max : {{data.max_duration_time}}</li>');
                        {% endfor %}
                        document.write('</ul>');
                    {% else %}
                        document.write('<ul>');
                            document.write('<li>Total Duration Time Min : 0</li>');
                            document.write('<li>Total Duration Time Max : 0</li>');
                        document.write('</ul>');
                    {% endif %} 
                    document.write('<div><input type="checkbox" id="useallminmax" name="useallminmax" onclick="handleClick(this);"><label for="useallminmax">Use this all min max value</label></div>');
                    document.write('<div><a id="link_m" href="{% url 'mouseheatmapapp:gen_mousemovementhm' 0 %}">Mouse Movement Heatmap</a><div>');
                    document.write('<div><a id="link_d" href="{% url 'mouseheatmapapp:gen_durationtimehm' 0 %}">Mouse Duration Heatmap</a><div>');
                    document.write('<div><a id="link_c" href="{% url 'mouseheatmapapp:gen_mouseclickhm' 0 %}">Mouse Click Heatmap</a><div>');
                    document.write('<div>Duration Time Total in MS Unit: '+durationTimeTotal+' and Min. Unit:'+(((durationTimeTotal)/1000)/60)+'<div>');
                    document.write('<div><table id="example" class="display" style="width:100%">');
                    document.write('<thead><tr><th>UNIX_TIMESTAMP_MS</th><th>DURATION_TIME_MS</th><th>CLIENTX</th><th>CLIENTY</th><th>MOVEMENTX</th><th>MOVEMENTY</th><th>LAST_MOUSE_MOVEMENT_MS</th><th>MOUSE_CLICKED</th></tr></thead>');
                    document.write('<tbody>');
                    var durationData=0;
                    
                    for(var i = 0; i < results.data.length; i++) {
                        document.write('<tr><td>'+(results.data[i].UNIX_TIMESTAMP_MS)+'</td>');
                        if(i < results.data.length-1){
                            durationData = (results.data[i+1].UNIX_TIMESTAMP_MS)-(results.data[i].UNIX_TIMESTAMP_MS);
                            results.data[i]['DURATION_TIME_MS']=durationData.toString();
                            document.write('<td>'+durationData+'</td>');
                        }else{
                            durationData=0;
                            results.data[i]['DURATION_TIME_MS']=durationData.toString();
                            document.write('<td>'+durationData+'</td>');
                        }
                        document.write('<td>'+results.data[i].CLIENTX+'</td>');
                        document.write('<td>'+results.data[i].CLIENTY+'</td>');
                        document.write('<td>'+results.data[i].MOVEMENTX+'</td>');
                        document.write('<td>'+results.data[i].MOVEMENTY+'</td>');
                        document.write('<td>'+results.data[i].LAST_MOUSE_MOVEMENT_MS+'</td>');
                        document.write('<td>'+results.data[i].MOUSE_CLICKED+'</td></tr>');
                    }
                    document.write('</tbody></table><div>');
                    $(document).ready(function () {
                    $('#example').DataTable(
                        {
                            "pageLength": 20,
                        }
                    );
                    });
                    // //จัดรูปแบบสำหรับแสดงผลบน heatmap.js
                    sessionStorage.setItem("heatmapData", JSON.stringify(results));
                    console.log(results);
                },
                header: true,
            });
        });
        function handleClick(cb) {
            // alert("Clicked, new value = " + cb.checked);
            const link_m = document.querySelector('#link_m');
            const link_d = document.querySelector('#link_d');
            const link_c = document.querySelector('#link_c');
            if(cb.checked){
                link_m.href = "{% url 'mouseheatmapapp:gen_mousemovementhm' 1 %}";
                link_d.href = "{% url 'mouseheatmapapp:gen_durationtimehm' 1 %}";
                link_c.href = "{% url 'mouseheatmapapp:gen_mouseclickhm' 1 %}";
            }
            else{
                link_m.href = "{% url 'mouseheatmapapp:gen_mousemovementhm' 0 %}";
                link_d.href = "{% url 'mouseheatmapapp:gen_durationtimehm' 0 %}";
                link_c.href = "{% url 'mouseheatmapapp:gen_mouseclickhm' 0 %}";
            }
            alert(link_d.href);

        }
    </script>
</body>

mouseheatmap/mouseheatmapapp/templates/mouseheatmapapp/read_csv.html
{% load static %}
<link rel="stylesheet" href="{% static 'mouseheatmapapp/style.css' %}">

{% if latest_heatmap_info_list %}
    <ul>
    {% for info in latest_heatmap_info_list %}
        <li><a href="{% url 'mouseheatmapapp:detail' info.id %}">{{ info.max_duration_time }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No data are available.</p>
{% endif %}

mouseheatmap/mouseheatmapapp/templates/mouseheatmapapp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'mouseheatmapapp:detail' question.id %}">Vote again?</a>